#IMAGEN UTILIZA JAVA 24 COMO BASE
FROM openjdk:24-jdk-slim

#CREA DIRECTORIO DE TRABAJO EN EL CONTENEDOR
WORKDIR /app

#COPIA ARCHIVO .JAR DEL PROYECTO AL CONTENEDOR
#SE RENOMBRA A app.jar PARA QUE SEA MAS FACIL DE MANEJAR
COPY target/petevents-0.0.1-SNAPSHOT.jar app.jar

#COPIAMOS ARCHIVO DE LA WALLET AL CONTENEDOR
#SE RENOMBRA A /app/wallet PARA QUE SEA MAS FACIL DE MANEJAR
COPY WALLET_SEMANA_1 /app/wallet

#SE DECRALA EXPLICITAMENTE QUE LA VARIABLE DE ENTORNO TNS_ADMIN APUNTE A LA RUTA DE LA WALLET
ENV TNS_ADMIN=/app/wallet

#PUERTO EN EL QUE SE EJECUTARA LA APLICACION
EXPOSE 8080

#COMANDO POR DEFECTO PARA EJECUTAR LA APLICACION AL INICIAR EL CONTENEDOR
ENTRYPOINT ["java", "-jar", "app.jar"]